version: "3.2"
services:
  qingscan:
    image: daxia/qingscan:20211220_02
    container_name: qingscan
    #    network_mode: "host"
#    volumes:
#      - type: bind
#        source: "../../"
#        target: "/root/qingscan"
    ports:
      - "8000:8000"
      - "13306:3306"
    stdin_open: true
    tty: true
    command: /bin/bash -c "php /root/qingscan/safe.php"
