name: dismap
label: Dismap
description: 资产识别工具
image: daxia/qingscan-dismap:latest
command: docker run --rm --network qingscan-net {image} --task-id={task_id} --callback={callback_url} --target={target}
enabled: true
