version: "3.2"
services:
  mysqlserver:
    image: mysql:5.6
    container_name: mysqlser
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - TZ=Asia/Shanghai
    volumes:
      - type: bind
        source: "./mysql"
        target: "/var/lib/mysql"
    ports:
      - "33306:3306"
  qingscan:
    image: registry.cn-beijing.aliyuncs.com/daxia/qingscan:20211231_01
    container_name: qingscan
    network_mode: "host"
    volumes:
      - type: bind
        source: "./files"
        target: "/root/files"
    #    ports:
    #      - "8000:8000"
    stdin_open: true
    tty: true
    command: /bin/bash -c "php /root/qingscan/safe.php"
