version: "3.2"
services:
  mysqlserver:
    image: mysql:5.7
    container_name: mysqlser
    environment:
      - MYSQL_DATABASE=QingScan
      - MYSQL_ROOT_PASSWORD=123
      - TZ=Asia/Shanghai
    ports:
      - "33306:3306"
    restart: always
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
  qingscan:
    image: registry.cn-chengdu.aliyuncs.com/qingscan/qingscan:20221201
    container_name: qingscan
    #    network_mode: "host"
    links:
      - mysqlserver:mysql_addr
    volumes:
      - type: bind
        source: "./files"
        target: "/root/files"
    ports:
      - "8000:8000"
    restart: always
    stdin_open: true
    tty: true
    command: /bin/bash -c "php /root/qingscan/safe.php"
  awvs:
    image: secfa/docker-awvs
    container_name: awvs
    ports:
      - "13443:3443"
    restart: always