version: "3.2"
services:
  qingscan:
    image: registry.cn-beijing.aliyuncs.com/daxia/qingscan:20211219_10
    container_name: qingscan
    #    network_mode: "host"
#    volumes:
#      - type: bind
#        source: "../../"
#        target: "/root/qingscan"
    ports:
      - "8000:8000"
      #- "13306:3306"
    stdin_open: true
    tty: true
    command: /bin/bash -c "php /root/qingscan/safe.php"
