version: "3.2"
services:
  qingscan:
    image: daxia/qingscan:20211216_01
    container_name: qingscan
#    network_mode: "host"
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: /bin/bash -c "php /root/qingscan/safe.php"
